
cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
)

cc_binary(
    name = "day01",
    srcs = ["day1.cpp"],
)

cc_binary(
    name = "day02",

    srcs = ["day2.cpp"],
)

cc_binary(
    name = "day03",
    srcs = ["day3.cpp"],
)

cc_binary(
    name = "day04",
    data = ["input/input_day4.txt"],
    srcs = ["day4.cpp"],
)

cc_binary(
    name = "day05",
    data = ["input/input_day5.txt"],
    srcs = ["day5.cpp"],
)

cc_binary(
    name = "day06",
    data = ["input/input_day6.txt"],
    srcs = ["day6.cpp"],
)

cc_binary(
    name = "day07",
    data = ["input/input_day7.txt"],
    deps=[
      "@com_github_google_benchmark//:benchmark_main",

    ],
    srcs = ["day7.cpp"],
)
